### ISSUE TITLE
KeyError:'dataList'

### ISSUE THREAD

**Issue by Krishnaj-20** [mpepping/solarman-mqtt#28] opened 2022-04-14 11:12 UTC
Hi 

This might be a stupid question but when i try and run the python script I get KeyError:'dataList'

Would you be able to assist with this?

Regards

**Comment by srk23** [comment] 2022-05-11 12:49
I am getting the same error...

**Comment by mpepping** [comment] 2022-05-13 20:27
Good to hear, @srk23. @Krishnaj-20, is that also applicable to your setup? I'm in the process of adding better error handling for this.

**Comment by giovanne123** [comment] 2022-07-19 12:20
Hm, same error.
It was working and suddenly stopped working.
No idea :-(

```
INFO:root:2022-07-19 14:03:27 - Inverter DeviceState: 1 -> Publishing to MQTT ...
INFO:root:2022-07-19 14:04:29 - Inverter DeviceState: 1 -> Publishing to MQTT ...
INFO:root:2022-07-19 14:05:32 - Inverter DeviceState: 1 -> Publishing to MQTT ...
INFO:root:2022-07-19 14:06:34 - Inverter DeviceState: 1 -> Publishing to MQTT ...
INFO:root:2022-07-19 14:07:36 - Inverter DeviceState: 1 -> Publishing to MQTT ...
INFO:root:2022-07-19 14:08:38 - Inverter DeviceState: 1 -> Publishing to MQTT ...
Traceback (most recent call last):
  File "run.py", line 14, in <module>
    main()
  File "run.py", line 10, in main
    solarman.main()
  File "/home/pi/solarman-mqtt/solarman/__init__.py", line 184, in main
    single_run(args.file)
  File "/home/pi/solarman-mqtt/solarman/__init__.py", line 62, in single_run
    inverter_data_list = ConstructData(inverter_data).device_current_data
  File "/home/pi/solarman-mqtt/solarman/api.py", line 97, in __init__
    self.device_current_data = self.construct_data()
  File "/home/pi/solarman-mqtt/solarman/api.py", line 104, in construct_data
    if self.data["dataList"]:
KeyError: 'dataList'
```

**Comment by giovanne123** [comment] 2022-07-19 12:53
Hm, now it is starting to work again:

```
KeyError: 'dataList'
Traceback (most recent call last):
  File "run.py", line 14, in <module>
    main()
  File "run.py", line 10, in main
    solarman.main()
  File "/home/pi/solarman-mqtt/solarman/__init__.py", line 184, in main
    single_run(args.file)
  File "/home/pi/solarman-mqtt/solarman/__init__.py", line 62, in single_run
    inverter_data_list = ConstructData(inverter_data).device_current_data
  File "/home/pi/solarman-mqtt/solarman/api.py", line 97, in __init__
    self.device_current_data = self.construct_data()
  File "/home/pi/solarman-mqtt/solarman/api.py", line 104, in construct_data
    if self.data["dataList"]:
KeyError: 'dataList'
^C
root@HRG-CoreServer:/home/pi/solarman-mqtt# while true; do python3 run.py -s; sleep 60s; done
INFO:root:2022-07-19 14:51:24 - Inverter DeviceState: 1 -> Publishing to MQTT ...
INFO:root:2022-07-19 14:52:26 - Inverter DeviceState: 1 -> Publishing to MQTT ...
INFO:root:2022-07-19 14:53:29 - Inverter DeviceState: 1 -> Publishing to MQTT ...

```

Can it be that there is a max request for the solarman API ? (for my tests i call the single run each 60sec)

**Comment by finfin82** [comment] 2022-10-08 16:29
Same here - are there any news for that problem?
I realy wanna use this cool solution to grab my inverter data.
Will there be a fix in the main-branch for that?
including property-naming (loggerid-> loggerSN)

**Comment by mpepping** [comment] 2022-10-09 11:29
Seem like that `dataList` key is missing in some occurances? There's a small update in the main-branch / v0.6.2 that should address this. Can you give this a go, @giovanne123, @finfin82 ?

`docker pull ghcr.io/mpepping/solarman-mqtt:0.6.2` or `docker pull ghcr.io/mpepping/solarman-mqtt:latest`

**Comment by giovanne123** [comment] 2022-10-12 15:00
Thanks, I will give it a try.
Yesterday I got all the time:
```
PiServer:/home/pi/solarman-mqtt/NEW_10-2022/solarman-mqtt#  python3 run.py -s
Traceback (most recent call last):
  File "run.py", line 14, in <module>
    main()
  File "run.py", line 10, in main
    solarman.main()
  File "/home/pi/solarman-mqtt/NEW_10-2022/solarman-mqtt/solarman/__init__.py", line 184, in main
    single_run(args.file)
  File "/home/pi/solarman-mqtt/NEW_10-2022/solarman-mqtt/solarman/__init__.py", line 76, in single_run
    inverter_device_state = inverter_data["deviceState"]
KeyError: 'deviceState'

```
I'm not sure why.
But today it started to work:
```
PiServer:/home/pi/solarman-mqtt/NEW_10-2022/solarman-mqtt# python3 run.py -s
2022-10-12 16:53:14 - Inverter DeviceState: 1 -> Publishing to MQTT ...
2022-10-12 16:54:16 - Inverter DeviceState: 1 -> Publishing to MQTT ...
2022-10-12 16:55:19 - Inverter DeviceState: 1 -> Publishing to MQTT ...
2022-10-12 16:56:21 - Inverter DeviceState: 1 -> Publishing to MQTT ...
```
I will check if it will run without dataList error...

**Comment by mpepping** [comment] 2022-10-15 10:06
Have seen API rate limiting in the past for myself. The (default) interval of 5 minutes works OK for me. A polling interval of a minute (your example) doesn't seem that frequent .. but maybe it's useful to test with a higher interval.

**Comment by giovanne123** [comment] 2022-10-28 08:43
I will try to change to 5min, 
but otherside I have running it again since my last post for now ~2week without a problem and 1min intervall. It's wirred and a not reproduceable behaviour:-(

**Comment by giovanne123** [comment] 2022-12-15 17:12
FYI, no change for me with 5min intervall too:

With newest I get - "deviceState" error:
```
Traceback (most recent call last):
  File "run.py", line 14, in <module>
    main()
  File "run.py", line 10, in main
    solarman.main()
  File "/home/pi/solarman-mqtt/NEW_10-2022/solarman-mqtt/solarman/__init__.py", line 184, in main
    single_run(args.file)
  File "/home/pi/solarman-mqtt/NEW_10-2022/solarman-mqtt/solarman/__init__.py", line 76, in single_run
    inverter_device_state = inverter_data["deviceState"]
KeyError: 'deviceState'

```


With older version - "dataList" error:
```
Traceback (most recent call last):
  File "run.py", line 14, in <module>
    main()
  File "run.py", line 10, in main
    solarman.main()
  File "/home/pi/solarman-mqtt/solarman/__init__.py", line 184, in main
    single_run(args.file)
  File "/home/pi/solarman-mqtt/solarman/__init__.py", line 62, in single_run
    inverter_data_list = ConstructData(inverter_data).device_current_data
  File "/home/pi/solarman-mqtt/solarman/api.py", line 97, in __init__
    self.device_current_data = self.construct_data()
  File "/home/pi/solarman-mqtt/solarman/api.py", line 104, in construct_data
    if self.data["dataList"]:
KeyError: 'dataList'
```

I think we can close the issue, because only I have this problem and it seems to work for the others. 
(maybe I will also change to modbus to read the inverter data locally without cn cloud)

**Comment by mpepping** [comment] 2023-01-04 13:21
Interesting error, @giovanne123. I'm curious to see what data is in the debug output. Is it's possible for you to do a run with `"debug": true` added to your config file? I'm especially interested in the block:

```text
INFO:root:{
    "code": null,
    "deviceId": 123456790,
    "deviceSn": "123456790123456790",
    "deviceState": 3,
    "deviceType": "INVERTER",
    "msg": null,
    "requestId": "123456790",
    "success": true
}
```

Just to learn what is in the deviceState key or the whole inverter_date object in the data you receive back, on the moment the run errors.

Now, a fix is added in the latest code in the main branch, to catch the `KeyError: 'deviceState'` error .. but it will effectively just skip and try again in the next iteration. Since you said that the error occurs every now and then, this should handle that. Still it would be nice to know what is in the actual data you get back from the API.

**Comment by giovanne123** [comment] 2023-01-04 19:02
Hm, there is no (or empty or not found) INVERTER part that time the error occurs:
This is the output (I inserted some xxx for some data)

```
python3 run.py -s
INFO:root:{
    "batteryPower": null,
    "batterySoc": null,
    "chargePower": null,
    "code": null,
    "dischargePower": null,
    "generationPower": 2.0,
    "generationTotal": 253.0,
    "gridPower": null,
    "irradiateIntensity": null,
    "lastUpdateTime": 1672845175.0,
    "msg": null,
    "purchasePower": null,
    "requestId": "xxxxxxxxxxxxxxxxxxx",
    "success": true,
    "usePower": null,
    "wirePower": null
}
INFO:root:{
    "code": "2101xxx",
    "msg": "device not found",
    "requestId": "xxxxxxxxxxxxxxxxxxx",
    "success": false
}
INFO:root:{}
INFO:root:{
    "code": null,
    "deviceId": 214xxxxxx,
    "deviceSn": "4111xxxxxx",
    "deviceState": 3,
    "deviceType": "COLLECTOR",
    "msg": null,
    "requestId": "xxxxxxxxxxxxxxxxxxx",
    "success": true
}
INFO:root:{
    "AT+UPGRADE_Command_Supported": "255",
    "Batch_Command_Supported": "1",
    "Data_Acquisition_Period": "60",
    "Data_Uploading_Period": "1",
    "Embedded_Device_SN": "4111xxxxxx",
    "Extended_Function": "7",
    "Extended_System_Version": "V1.1.00.0F",
    "Heart_Rate": "120",
    "IV_Curve_Supported": "1",
    "Max._No._of_Connected_Devices": "1",
    "Method_Of_Protocol_Upgrade": "255",
    "Module_Version_No": "MW3_15U_5406_1.47",
    "Offset_time": "1672844923",
    "Signal_Strength": "49",
    "Support_AntiBackflow_Function_Instructions": "Enable",
    "Support_Reporting_Upgrading_Progress": "1",
    "Total_running_time": "1"
}
Traceback (most recent call last):
  File "run.py", line 14, in <module>
    main()
  File "run.py", line 10, in main
    solarman.main()
  File "/home/pi/solarman-mqtt/NEW_10-2022/solarman-mqtt/solarman/__init__.py", line 184, in main
    single_run(args.file)
  File "/home/pi/solarman-mqtt/NEW_10-2022/solarman-mqtt/solarman/__init__.py", line 76, in single_run
    inverter_device_state = inverter_data["deviceState"]
KeyError: 'deviceState'
```

**Comment by mpepping** [comment] 2023-01-05 20:08
So the object is completely empty. Wasn’t expecting that! Question is then if the data is also not present in the Solarman cloud graphs. That would suggest that it’s also missing from the data that was sent to the cloud service. 
Version v0.8.0 (or the main branch) will handle this error, by skipping the run and just wait for the next iteration. Can’t think of a valid way to deal with this in an other way for now.

**Comment by giovanne123** [comment] 2023-01-05 20:24
OK, I will update to v0.8.0
And we can close this issue, because nobody else seems to have the same problem.
I will only use this on demand to read e.g. firmware/settings infos before/after requesting an update...
For live data I already switched to local modbus readings.

**Closed** 2023-01-05 20:26 UTC
